### ISSUE TITLE
Support for ultrasonic distance sensor

### ISSUE THREAD

**Issue by happytm** [NanoBeacon/config-files#1]
Thank you for great product at such a low cost.

Is it possible to use ultrasonic sensor linked below with NanoBeacon ?

https://universal-solder.ca/downloads/HC-SR04_Ultrasonic_arduino_guide.pdf

Thanks.

**Comment by NanoBeacon** [comment]
Hi happytm,

Thank you for your interest in the NanoBeacon.

The IN100 NanoBeacon supports I2C communication and One-Wire Sensor control. It also has features such as an on chip ADC that can also serve a purpose in receiving sensor data. Looking at the guide you attached, I see several issues. First, the sensor communicates through two pins, the trig and the echo. This is not supported by the IN100 state machine. Second, recommended operating voltage is 1.2 - 3.6 Volts. The sensor requires +5V, meaning some sort of external power source or circuitry would be needed to power the ultrasonic sensor.

However, despite these issues, I see no immediate problems with connecting the IN100 and ultrasonic sensor to a mutual MCU. The MCU would handle the sensor trig and echo pins, and then place the calculation result into the IN100 advertising payload and transmit this information to a receiver.

**Comment by happytm** [comment]
Thank you for your quick reply. Can you elaborate how the MCU will communicate with IN100?

**Comment by NanoBeacon** [comment]
Hi happytm

[IN100_Host Conroller_Sample_C_Code.zip](https://github.com/NanoBeacon/config-files/files/10817942/IN100_Host.Conroller_Sample_C_Code.zip)

[NanoBeacon Host Controller API Guide (3).pdf](https://github.com/NanoBeacon/config-files/files/10817946/NanoBeacon.Host.Controller.API.Guide.3.pdf)

Refer to the Host Controller API and sample code linked here.

The MCU communicates to the IN100 through the UART pins, the same used by the development board to communicate with the programmer board. For the QFN18 packaging of the IN100 (this is the one on the development board), these are pins GPIO 0 and GPIO 1.

If you have further questions, I encourage you to reach out to me directly at aidan.martens@inplay-tech.com.

**Comment by happytm** [comment]
Thank you so much Aidan.
