### ISSUE TITLE
advertising interval cannot exceed 20 second?

### ISSUE THREAD

**Issue by Saranya-karan** [NanoBeacon/config-files#10]
![bcn](https://github.com/user-attachments/assets/72723ac4-1b1e-476b-b5a0-6b8d95265ad0)

when i try to advertise data once in 60 seconds,it just pop up that "contact inplay support if adv. interval is greater than 20s".
can we achieve the advertising interval greater than 20s with in100 beacon?

**Comment by NanoBeacon** [comment]
Hi Saranya,

Please reach out to aidan.martens@inplay-tech.com and I will will explain the situation.

**Comment by Saranya-karan** [comment]
> Hi Saranya,
> 
> Please reach out to [aidan.martens@inplay-tech.com](mailto:aidan.martens@inplay-tech.com) and I will will explain the situation.

u just closed the issue here,and i dont get any reply via mail???????
can u response?

**Comment by NanoBeacon** [comment]
Hi Saranya,

Yesterday was veterans day in the US so I was not in the office. I have since responded this morning. Please check your email again. You can follow up again here if you did not receive anything.

**Comment by Saranya-karan** [comment]
understand.thank you for the response
