### ISSUE TITLE
IN100 nanobeacon as a receiver/scanner 

### ISSUE THREAD

**Issue by y-runwal** [NanoBeacon/config-files#8]
Can I use INPlay's IN100 nanobeacon as a receiver/scanner to scan the nearby available beacons and send their data to a microcontroller?

**Comment by StevePoston** [comment]
Hi y-runwal,
The simple answer is No it can't act as a receiver/scanner.  It only has an RF Transmitter on the front end.
Here's the block diagram of the IN100 (image from the [IN100 datasheet](https://inplay-tech.com/s/IN100-datasheet_Updated.pdf)):
![in100_block_diagram](https://github.com/user-attachments/assets/e11a3e4a-dc7d-4934-814e-044c8fd50485)

**Comment by y-runwal** [comment]
Ohk! Thanks for reply!!
But here is what I found. That's why asked.
![image](https://github.com/user-attachments/assets/d8fcf1d9-46e3-412c-8443-e402751fc0d2)

**Comment by y-runwal** [comment]
![image](https://github.com/user-attachments/assets/4673d86b-2c9a-438d-94b0-95a44d33550a)
this one too

**Comment by y-runwal** [comment]
If not IN100, can I use IN610 series?

**Comment by StevePoston** [comment]
I would say yes for the IN610 series, but I've not evaluated that device.  I'd suggest you contact [support@inplay-tech.com](mailto:contact@inplay-tech.com), for more information on their range of Bluetooth Transceivers.  Adrian there is always of great help.

**Comment by y-runwal** [comment]
Ok thanks!
Closing this as completed.
